title: Nur Kholifah # your name (or website title) here
logo: "pictures.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center"> <a href="https://www.linkedin.com/in/nur-kholifah-9581bb215">LinkedIn</a> | <a href="https://github.com/khlfh">GitHub</a></p>
  I am a fresh graduate in Mathematics with strong analytical skills and data-oriented mindset. Actively involved in organizations and excelling academically.
  <br><br>
  Looking for job opportunities to develop into a professional career.
  <br><br>
  
  



theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
