title: Nur Kholifah # your name (or website title) here
logo: "pictures.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center"> <a href="https://www.linkedin.com/in/nur-kholifah-9581bb215">LinkedIn</a> | <a href="https://github.com/khlfh">GitHub</a></p>
  I am a fresh graduate in Mathematics focusing on Statistics with strong analytical skills and data-oriented mindset. 
  <br><br>
  Actively involved inorganizations and excelling academically.
  <br><br>
  Experienced as a group leader for the final assignment of data analytics training which was carried out for 6 months with an excellent predicate score for final project.
  <br><br>
  Looking for job opportunities that provide opportunities to develop into a professional career.
  <br><br>
  
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
